#! /usr/bin/bash

sxhkd &
yabar &

bspc config border_width        1
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled  true

bspc monitor -d             7 8 9 0
